DROP DATABASE IF EXISTS movies;
CREATE DATABASE movies;

\c movies

DROP TABLE IF EXISTS users;
CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS queries;
CREATE TABLE queries (
	id SERIAL PRIMARY KEY,
	user_id INT NOT NULL,
	search_term VARCHAR(255) NOT NULL,
	search_date DATE DEFAULT CURRENT_DATE,
	FOREIGN KEY (user_id) REFERENCES users(id)
	);